version: "3.7"

services:
  database:
    image: postgres
    container_name: database_ignite
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=dockerPostgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=alugacar
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: alugacar
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database

volumes:
    pgdata:
        driver: local